# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4cb06cadf14745682a334d36b58807519e497389cdd4adb51bb0045fcb6f749216f5c5d5c26921567ff13aaeab0f4e452123b3b37652b085ebfe237157248a96

test:
  secret_key_base: bb0bb5d6f8fc40f455b1646867be9405a091fd8ecc0658c7f681890d17a385a4bed471c6855527277db2fbdcf542618634db3aea6569818b5f27118194fa6e12

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
